flow_power_rules:
  - 'country_development_cooperative'
  - 'quadratic_average_development'
  - 'country_development_mercantilism'
  - 'country_power_cooperative'
  - 'country_development_mercantilism_cooperative'
  - 'country_power_mercantilism_cooperative'
  - 'country_development'
  - 'country_power'
  - 'country_power_mercantilism'
  - 'average_development'
  - 'quadratic_average_provincial_trade_power'
  - 'average_provincial_trade_power'
  - 'quadratic_total_development'
  - 'quadratic_total_provincial_trade_power'
  - 'total_development'
  - 'total_provincial_trade_power'